### ISSUE TITLE
acbuild should remove /etc/resolv.conf

### ISSUE THREAD

**Issue by crawford** [containers/build#153]
I'm trying to use ubuntu-14.04-server-cloudimg-amd64-root as the base for my ACI, but I am unable to resolve host names when using `acbuild run`. It looks like systemd-nspawn is trying to populate `/etc/resolv.conf`, but is getting confused because that file is a symlink. I think it should be safe for acbuild to ensure that that file doesn't exist by the time that systemd-nspawn is run.

**Comment by dgonyeo** [comment]
Related: https://github.com/appc/acbuild/issues/142

**Comment by jonboulle** [comment]
hrm, this means that the same ACI exhibits different behaviour when run under `acbuild` or under `rkt` (which doesn't execute the *apps* directly with `systemd-nspawn`), which is unfortunate

**Comment by dgonyeo** [comment]
Think it'd be better to have a stance of just doing what rkt does? I wonder if crawfords image is also broken under rkt with respect to dns.

**Comment by crawford** [comment]
I still haven't run it under `rkt` yet. Someone is supposed to help me with another issue after lunch...

**Comment by jonboulle** [comment]
![after lunch](http://i.imgur.com/9xTULpr.gif)

**Comment by urzds** [comment]
https://github.com/coreos/coreos-baremetal/issues/67#issuecomment-188879911 is partly related.

**Comment by dghubble** [comment]
Any clarity on correct behavior? I was tripped up earlier when an acbuild image (development) had an `/etc/resolv.conf`, while its counterpart docker image converted to an ACI (production) did not.

(Until I can have rktnetes use an ACI directly, I'm stuck paying attention to the what happens between image transforms)

**Comment by jd3nn1s** [comment]
Any update on this? I've run into issues where an /etc/resolv.conf was created & stored by acbuild and I had to add an acbuild step to remove it for the produced container image to function correctly.

**Comment by dgonyeo** [comment]
I can put together a PR to remove this, and it would be like 3 lines, but it would always remove it regardless of whether or not the command run was intending to populate it.

In other words, it would be hard to tell the difference between the following commands:
```
acbuild run -- echo "hello, world!"
acbuild run -- /bin/sh -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
```
Should I just always blindly remove it if it didn't exist before the `run` command, and rely on users having to use the `acbuild copy` to populate `/etc/resolv.conf` ?

**Comment by crawford** [comment]
How feasible is it to remove it before run and then if it exists after the command has finished, leave a marker so that it isn't removed in future invocations of `run`. Maybe that's to complex to easily reason about.

**Comment by dgonyeo** [comment]
If I indiscriminately remove it before run it will always exist after run, because `systemd-nspawn` creates it if it doesn't exist, so I don't think that's a viable solution.

**Comment by crawford** [comment]
I think requiring `acbuild copy` is probably fine.

**Comment by dgonyeo** [comment]
This also has the caveat that if you do an `acbuild copy` to populate `/etc/resolv.conf`, and then do another `acbuild run` command, your populated `/etc/resolv.conf` will be deleted for you.

**Comment by kfirufk** [comment]
when I run "acbuild --debug copy /etc/resolv.conf /etc/resolv.conf"
and then "acbuild --debug run -- cat /etc/resolv.conf" then I see the unmodified version. 

any solution for this ?

**Comment by dgonyeo** [comment]
@kfirufk An easy solution for you should be to swap the order of those, or add `--engine=chroot` to the `run` command.

**Comment by kfirufk** [comment]
ok.. i use docker://alpine:edge image. i noticed that when the image is first started, /etc/resolv.conf is configured properly to google's dns. after a minute or two /etc/resolv.conf is replaced and now contains 'nameserver 127.0.0.53' which causing me problem cause there is no dns server in the lopback device as far as i understand.

running 'acbuild --engine=chroot run -- cat /etc/resolv.conf' shows the correct /etc/resolv.conf. does it mean that I need to run every commad with '--engine=chroot' ? and @dgonyeo, you wrote to swap the order of those... what do you mean exactly ?

**Comment by dgonyeo** [comment]
Every time you do an `acbuild run` command without a `--engine=chroot` it will modify your `/etc/resolv.conf`. If you want to set what's in the `/etc/resolv.conf` file inside your container during the build, make sure you copy it in _after_ you've done any `acbuild run` commands (unless you put the `--engine=chroot` flag on all run commands)

**Comment by squeed** [comment]
If you want to make the host's `resolv.conf` available for for reading, you could bind-mount read-only the hosts's `/etc/resolv.conf` in to the container.

This does not solve the write / copy problem.

**Comment by kfirufk** [comment]
so yeah.. adding --engine=chroot to all run commands resolved the issue.
