### ISSUE TITLE
"Ubuntu Core" link broken

### ISSUE THREAD

**Issue by jmarley** [containers/build#247]
https://github.com/appc/acbuild/blob/master/Documentation/subcommands/begin.md#starting-with-a-local-pre-existing-rootfs

The link that points to Ubuntu Core is broken. I tried to hunt down exactly where the downloads page is, but I eventually was routed to Ubuntu Snappy and wasn't sure if that was the correct download.

Thanks,
Jason

**Comment by dgonyeo** [comment]
It looks like Canonical changed the layout of their site.

The link should now point to
http://cdimage.ubuntu.com/ubuntu-core/xenial/daily-preinstalled/current/

I'll make a PR to fix this. Thanks for reporting it!

**Comment by markshuttle** [comment]
Hi think you actually want this:

http://cdimage.ubuntu.com/ubuntu-base/xenial/daily/current/

My bad :)

**Comment by dgonyeo** [comment]
Because I rewrote the documentation for `begin` in the unmerged https://github.com/containers/build/pull/276, I just slipped the fix into there, to save myself from merge conflict headaches in the future. That PR will hopefully land soon.
