### ISSUE TITLE
Better documentation for 'script' command

### ISSUE THREAD

**Issue by cdrage** [containers/build#255]
There's very little documentation in the --help command as well as the documentation in regards to using the `acbuild script` command.

The only example I found was https://github.com/containers/build/blob/master/examples/apache/build-apache.acb

Let's create some docs for this _awesome_ command!

**Comment by jonboulle** [comment]
Good point, there should be a subcommands document for this! Would you be
up for taking a first pass?

**Comment by cdrage** [comment]
@jonboulle yaya, i'll get some PR up later next week

**Comment by cdrage** [comment]
This is done :)
