### ISSUE TITLE
Acbuild begin - Errors from beginFromLocalDirectory are being swallowed in Begin

### ISSUE THREAD

**Issue by tjabell** [containers/build#270]
Hi, 

I was trying to start a new build from a directory with `acbuild begin /path/to/rootfs` and it was only creating about half of the directories under `.acbuild/currentaci/rootfs` that had existed in the source directory.  After a little debugging, it looks like any errors that occur in beginFromLocalDirectory [https://github.com/containers/build/blob/master/lib/begin.go#L161](url) are swallowed in Begin [https://github.com/containers/build/blob/master/lib/begin.go#L96](url).  In this case it was swallowing a permission error when trying to copy the directory.

My Go-fu is pretty weak, but perhaps https://github.com/containers/build/blob/master/lib/begin.go#L96 should look like:
```
err = a.beginFromLocalDirectory(start)

if err != nil {
	return err
}
```

Thanks!

**Comment by jonboulle** [comment]
Great find! By my reading, that line should actually be `return a.beginFromLocalDirectory(start)` (since we don't want to continue on to the empty directory start).

Would you be interested in submitting a patch for this?
