### ISSUE TITLE
acbuild begin silently does nothing when run not by root

### ISSUE THREAD

**Issue by dimas** [containers/build#272]
I created rootfs folder with debootstrap, played with acbuild with no luck. Spent a lot of time before realised that "acbuild begin" actually copies files under .acbuild/currentaci/ and it fails to do so unless run under root user.
I assume this is because it tries to keep file ownership and just cannot create root-owned files. But it definitely makes sense to alert user when you cannot do something not just swallow problems. To me, failure to copy a single file already warrants non-zero exit code. Maybe with a command line option to change that behaviour.
Cheers

**Comment by dgonyeo** [comment]
Huh, I would expect it to create the files with the current user's permissions. This is definitely an issue.

**Comment by dimas** [comment]
To be honest, I know very little on how these things should work as I am very new to this. But if keeping original file owners/groups is important and files end up with these owners/groups in the image, then it is probably not the best idea to lose this information and if "acbuild begin" cannot keep that information even for a single file - it should really complain because it can be important as user will end up not with the files/permissions he thinks but with something else. No?

**Comment by dgonyeo** [comment]
Yeah you're right. Acbuild doesn't choke on it right now for convenience.
It should spit out a warning though. If you're feeling up to it feel free
to add a PR, otherwise I'll get to it in a couple days.
