### ISSUE TITLE
Difficulties with set-working-directory

### ISSUE THREAD

**Issue by swerter** [containers/build#280]
Hello
I'm having difficulties with `set-working-directory`. It somehow does not seem to work (or I don't know how). Here my build script:

```
acbuild --debug begin ./alpine-edge.aci
acbuild --debug run mkdir /hello
acbuild --debug set-working-directory /hello/
acbuild --debug run pwd
acbuild --debug run touch abc
acbuild --debug run ls
acbuild --debug write --overwrite hello.aci
```

which results in the output:
```
Beginning build with ./alpine-edge.aci
Running: [mkdir /hello]
Setting working directory to /hello/
Running: [pwd]
/
Running: [touch abc]
Running: [ls]
abc      dev      hello    lib      media    proc     run      srv      tmp      var
bin      etc      home     linuxrc  mnt      root     sbin     sys      usr
Writing ACI to hello.aci
warning: exec command was never set.
```
So it seems the working directory is still `/` instead of `/hello`. Can anybody help me? Is this a bug or am I missing something? Thanks.

**Comment by dgonyeo** [comment]
Sorry about the delay, the `set-working-directory` command only impacts
what rkt does, the `run` subcommand to acbuild doesn't use it. You can use
the `--working-dir` flag to the `run` subcommand to choose a working
directory.

**Comment by swerter** [comment]
Thanks a lot for your help. How about adding a small comment into the run documentation?

**Comment by dgonyeo** [comment]
Oh yeah, that should definitely be mentioned there. I'll put together a PR.

**Comment by nomasprime** [comment]
@dgonyeo I was expecting this to work like a Dockerfile WORKDIR. Is there a workaround for this? Having to pass --working-dir to run every time is a bit of a pain.

**Comment by cgonyeo** [comment]
`set-working-directory` doesn't work like this by design. All it does it update a line in a json file that rkt looks at later. The `--working-dir` flag is the way to set the working directory for a given `run` command.
