### ISSUE TITLE
Provide Image ID on "write"

### ISSUE THREAD

**Issue by trusch** [containers/build#305]
It would be nice to have acbuild output the image ID of the generated image. If not, you need to uncompress and hash the tarball contents by hand.

related to https://github.com/rkt/rkt/issues/3667

I would try to take care about this, PR will follow this week.

**Comment by lucab** [comment]
@dgonyeo any preferences on whether this should be part of `end` or `write`? Also, should this be opt-in or opt-out?

**Comment by dgonyeo** [comment]
It should definitely be part of `write`, as `end` will also be called in the event of build failures. I'm indifferent to it being opt-in or opt-out.

**Comment by lucab** [comment]
Fixed via https://github.com/containers/build/pull/306.
