### ISSUE TITLE
echo with acbuild run writes a file on the host

### ISSUE THREAD

**Issue by jharshman** [containers/build#310]
AcBuild Version: 
``` bash
$ acbuild version
acbuild version v0.4.0
appc version 0.8.5
```

Given the following line:
``` bash
acbuild run -- echo 'eval "$(rbenv init -)"' | tee /etc/profile.d/rbenv.sh
```
a file is generated on the host machine running acbuild rather than inside the container.  The end goal here is to have `eval "$(rbenv init -)"` written into the file `/etc/profile.d/rbenv.sh` within the container image.

Is this misuse on my part or a bug?

**Comment by dgonyeo** [comment]
What's happening here is the shell on the host is interpreting the pipe and running the tee command, instead of those things being passed into acbuild. You can invoke a shell inside of acbuild to do the pipe logic for you if you wish:

```bash
acbuild run -- /bin/sh -c 'echo \'eval "$(rbenv init -)"\' | tee /etc/profile.d/rbenv.sh'
```

**Comment by jharshman** [comment]
Thanks for the quick reply!  Seems to be something funky going on with the quotes though.
