### ISSUE TITLE
'Error: overlayfs not supported on your system' with LXD Container

### ISSUE THREAD

**Issue by justinmnoor** [containers/build#321]
Is it possible to build and run rkt images inside of an LXD container (for development purposes)? LXD does not support overlayfs according to lxd/lxc issue [#1878](https://github.com/lxc/lxd/issues/1878).

To no surprise, when I attempt build an image with acbuild I get the following error:

`overlayfs is not supported on your system`

My lxd container uses kernel version 4.4. I'm using the acbuild [build-nodejs.sh](https://github.com/containers/build/tree/master/examples/nodejs) example file.
 
It appears that there was a squash command built for this issue, as stated in [#18](https://github.com/containers/build/issues/18), but I don't see that command in acbuild version v0.4.0. I tried anyways and it didn't work.

Any thoughts?

**Comment by justinmnoor** [comment]
LXD has a [profile option](https://insights.ubuntu.com/2016/04/13/stephane-graber-lxd-2-0-docker-in-lxd-712/) for Docker containers which "seems" to have done the trick. You specify the profile when you launch your LXD container. It provides some special kernel modules, mounts, and nesting (because LXD is also a container). Perhaps there will be an RKT profile for LXD in the future :)

As mentioned my intention was to use acbuild for RKT. To the best of my knowledge, OCI is the main priority for RKT, therefore, I will close this.

**Comment by Kuchiriel** [comment]
Solved?

**Comment by justinnoor** [comment]
No. This was a previous attempt to try out RKT. I will say politely that RKT is messy, poorly documented, and has an unresponsive community, therefore, I decided against it. I'm actually using systemd-nspawn now. Also Docker is much more user friendly and has great documentation in comparison to RKT.

**Comment by Kuchiriel** [comment]
Upgrade and rebuild the kernel, restart computer then try again. For me it works. But I agree with you, I don't like monopolies not unix-like like Docker, but rkt is far from usable from the documentation perspective. :/

**Comment by justinnoor** [comment]
Glad it worked for you. I probably won't try RKT again hah. Good luck and thanks for reaching out.
