### ISSUE TITLE
New import path for xz package

### ISSUE THREAD

**Issue by xi2** [containers/build#327]
There is a new import path for the `xz` package used in `registry/fetch.go` (which you have also vendored). It is `github.com/xi2/xz`. The old one will cease to work at some point. Sorry for the inconvenience.

**Comment by cgonyeo** [comment]
Thanks for the heads up. The dependencies are vendored in this project, so nothing will break when the old import path is removed, and this project is no longer actively maintained so I see no reason to update it.
